import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Playpen_Sans, Outfit } from "next/font/google";

const playfair = Playpen_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-playfair",
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-outfit",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${outfit.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
